config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  authenticate :user, lambda { |u| u.admin? } do
    mount BeanstalkdView::Server, :at => "/beanstalkd"
  end

  root 'home#index'
  resources :recording_schedules do
    get 'log', to: 'recording_schedules/logs#show'
  end
  resource :time_zone, controller: :time_zones

end

app/models/recording_schedule.rb
class RecordingSchedule < ActiveRecord::Base
  serialize :days_of_week, JSON

  belongs_to :user

  validates :name, :start_time, :stop_time, presence: true
  validates :stream_url, url: true, presence: true
  validate :days_of_week_must_exist, if: :recurring?
  validates :start_on, presence: true, unless: :recurring?

  private

  def days_of_week_must_exist
    # Get the intersection of arrays.
    intersection = Date::DAYNAMES_MAP.values & (self.days_of_week || [])

    if self.days_of_week != intersection || self.days_of_week.blank?
      errors.add(:days_of_week, 'must be one or more days of the week')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :recording_schedules

  def iana_time_zone
    ActiveSupport::TimeZone::MAPPING[self.time_zone]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Forcing SSL in dev since it's mandatory in production.
  # For details see config/initializers/ssl_patch_for_development.rb
  force_ssl if Rails.env.development?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || recording_schedules_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def dropbox_oauth2
    @user = Services::CreateUser.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
       sign_in_and_redirect @user, :event => :authentication
       @user.remember_me!
       set_flash_message(:notice, :success, :kind => "Dropbox") if is_navigational_format?
     else
       redirect_to new_user_session_url
     end
  end
end

app/controllers/recording_schedules/logs_controller.rb
class RecordingSchedules::LogsController < ApplicationController
  before_action :authenticate_user!

  def show
    recording_schedule = current_user.recording_schedules.find(params[:recording_schedule_id]).decorate
    @log_content = if File.exists?(recording_schedule.logfile_name)
      File.readlines(recording_schedule.logfile_name)[0..500].join
    end || 'The logfile is empty.'
  end

end

app/controllers/recording_schedules_controller.rb
class RecordingSchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_to_time_zone, if: Proc.new { current_user.time_zone.blank? }

  def index
    @recording_schedules = RecordingSchedule.where(user_id: current_user.id).order(:name).decorate
  end

  def new
    @recording_schedule = RecordingSchedule.new
  end

  def create
    @recording_schedule = RecordingSchedule.new(recording_schedule_params).decorate
    @recording_schedule.user = current_user
    notifier = Services::ScheduleNotifier.new(@recording_schedule, RUFUS_SCHEDULER_CLIENT)

    if notifier.save
      redirect_to recording_schedules_path, flash: { success: 'Recording schedule added.' }
    else
      flash.now[:error] = "There were some problems with this recording schedule."
      render :new
    end
  end

  def destroy
    @recording_schedule = RecordingSchedule.find(params[:id]).decorate
    notifier = Services::ScheduleNotifier.new(@recording_schedule, RUFUS_SCHEDULER_CLIENT)
    flash_options = {}

    if notifier.destroy
      flash_options[:success] = 'Recording schedule removed.'
    else
      flash_options[:success] = 'Recording schedule not removed.'
    end

    redirect_to recording_schedules_path, flash_options
  end

  def edit
    @recording_schedule = RecordingSchedule.where(id: params[:id], user_id: current_user.id).first
  end

  def update
    @recording_schedule = RecordingSchedule.where(id: params[:id], user_id: current_user.id)
      .first
      .decorate
    notifier = Services::ScheduleNotifier.new(@recording_schedule, RUFUS_SCHEDULER_CLIENT)

    if notifier.save(recording_schedule_params)
      redirect_to recording_schedules_path, flash: { success: 'Changes saved.' }
    else
      flash.now[:error] = "There were some problems with this recording schedule."
      render :edit
    end
  end

  private

  def recording_schedule_params
    strip_blank_from_days_of_week(
      params
        .require(:recording_schedule)
        .permit(:duration, :stop_time, :name, :recurring,
         :start_on, :start_time, :stream_url, days_of_week: []
        )
    )
  end

  def redirect_to_time_zone
    redirect_to time_zone_path
  end

  def strip_blank_from_days_of_week(permittied_params)
    if permittied_params[:days_of_week].present?
      permittied_params[:days_of_week]
        .reject! {|i|i.blank?}
        .collect!(&:to_i)
    end
    permittied_params
  end
end

app/controllers/time_zones_controller.rb
class TimeZonesController < ApplicationController
  before_action :authenticate_user!

  def show

  end

  def update
    if current_user.update_attributes(time_zone_params)
      redirect_to session[:return_to] || recording_schedules_path
    else
      flash[:error] = "There were some problems"
      render :update
    end
  end

  private

  def time_zone_params
    params.require(:user).permit(:time_zone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    "#{controller_name} #{action_name}"
  end

  def current_class(return_class)
    if return_class
      'current'
    end
  end

  def rot13(content)
    content.tr("A-Ma-mN-Zn-z","N-Zn-zA-Ma-m").html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recording_schedules/logs_helper.rb
module RecordingSchedules::LogsHelper
end

app/helpers/recording_schedules_helper.rb
module RecordingSchedulesHelper
  def recording_status_class(recording_schedule)
    if Scheduler::RecordingProcess.new(recording_schedule).running?
      'recording'
    else
      'sleeping'
    end
  end

  def start_on_options
    (Date.today..Date.today+14).to_a.map {|d| [d.to_s(:long),d.to_s]}
  end
end

app/helpers/time_zones_helper.rb
module TimeZonesHelper
end

app/views/home/index.html.erb
<% content_for :callout do %>
  <div class="callout">
    <div class="description">
      <h2>Radio Shifter listens when you can't.</h2>
      <p>
        Scheduled streaming radio recordings sent to your Dropbox account.
      </p>
      <%= link_to recording_schedules_path, class: "button large green" do %>
        Get Started<i class="icon-dropbox"></i>
      <% end %>
    </div>
    <%= image_tag('home/product.png', class: 'product') %>
  </div>
<% end %>

<div class="callout-footer">
  <div class="quote">
    <p>
      <i class="icon-quote-left"></i>
      These guys operate on my wavelength.
    </p>
    <p><span><strong>- Gugliemo Marconi</strong>, Inventor of Radio.</span></p>
    <small><em>This is 100% unfounded.</em></small>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Radio Shifter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="<%=body_class%>">
  <div class="beta"><span>Beta</span></div>
  <%= render 'layouts/shared/nav' %>
  <%= render 'layouts/shared/flash' %>
  <%= yield :callout %>
  <div class="grid flex content">
    <%= yield %>
  </div>
  <div class="footer">
    <i class="icon-envelope"></i>
    <span class="encoded">
      <%= rot13(mail_to 'info@radioshifter.com', 'info@radioshifter.com') %>
    </span>
  </div>
</body>
</html>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash notice <%=key%>"><%= value %></div>
<% end -%>

app/views/layouts/shared/_nav.html.erb
<ul class="nav menu right">
    <li class="logo">
      <%= link_to root_path do %>
        <span>RADIO</span> shifter
      <% end %>
    </li>
    <li>
      <% if user_signed_in? %>
        <%= link_to recording_schedules_path do %>
          Dashboard
        <% end %>
        <ul>
          <li>
            <%= link_to destroy_user_session_path do %>
              Log Out
            <% end %>
          </li>
        </ul>
      <% else %>
        <%= link_to recording_schedules_path do %>
          <i class="icon-angle-right"></i>
          Log In
        <% end %>
      <% end %>
    </li>
  </ul>

app/views/recording_schedules/_details.html.erb
<div class="details">
  <% if recording_schedule.last_run_at %>
    <div>
      <small>
        <span>Last run at </span>
        <%= recording_schedule.last_run_at.in_time_zone(current_user.time_zone).to_s(:long)%>
      </small>
    </div>
    <div>
      <small><%= link_to 'Log', recording_schedule_log_path(recording_schedule) %></small>
    </div>
  <% end %>
</div>

app/views/recording_schedules/_form.html.erb
<%= form_for recording_schedule, as: :recording_schedule, url: url, html: { class: 'vertical' } do |f|%>
  <%= f.hidden_field :duration %>
  <div class="col_12">
    <%= f.label :name, "Recording Name" %>
    <%= f.text_field :name, placeholder: 'My Show' %>
  </div>
  <div class="col_12">
    <%= f.label :stream_url, "Stream URL" %>
    <%= f.text_field :stream_url, placeholder: 'http://servername.com:1234/some/audio/source' %>
    <span class="help-text">
      <%= mail_to 'info@radioshifter.com', 'Contact us' %> if you need help finding the Stream URL for the radio station you want to record.
    </span>
  </div>
  <ul class="tabs left">
    <li class="<%= current_class(recording_schedule.recurring?) %>">
      <a href="#tab_repeat_recording" data-recurring="true">Repeat Recording</a>
    </li>
    <li class="<%= current_class(!recording_schedule.recurring?)%>">
      <a href="#tab_record_once" data-recurring="false">Record Once</a>
    </li>
  </ul>
  <div class="time_range">
    <div class="start_at col_6">
      <%= f.label :start_time, "Start At" %>
      <%= f.text_field :start_time %>
    </div>
    <div class="col_6">
      <%= f.label :stop_time, "Stop At" %>
      <%= f.text_field :stop_time %>
    </div>
  </div>
  <%= f.hidden_field :recurring %>
  <div id="tab_repeat_recording" class="tab-content">
    <% if recording_schedule.errors[:days_of_week].present? %>
      <span class="error"><%= recording_schedule.errors[:days_of_week].join %></span>
    <% end %>
    <%= hidden_field_tag "recording_schedule[days_of_week][]", nil %>
    <% Date::DAYNAMES_MAP.each_pair do |day, i| %>
      <div class="col_4">
        <label class='clickable'>
          <%= f.check_box :days_of_week, {multiple: true }, i, nil %>
          <%= day %>
        </label>
      </div>
    <% end %>
  </div>
  <div id="tab_record_once" class="tab-content">
    <%= f.select :start_on, start_on_options,  {include_blank: 'Choose a day'} %>
  </div>
  <%= submit_tag 'Save', class: 'button green' %>
<% end -%>

app/views/recording_schedules/_no_schedules.html.erb
<div class="notice info">

  You don't have any recording schedules setup yet.

  <%= link_to new_recording_schedule_path, class: 'button green' do %>
    Create My First Recording Schedule
  <% end -%>
</div>

app/views/recording_schedules/_recording_schedule_card.html.erb
<div class="recording_schedule_card">
  <div class="col_10">
    <h5 class="title">
      <i class="icon-circle recording-status <%=recording_status_class(recording_schedule)%>"></i>
      <%= recording_schedule.name %>
    </h5>
    <p>
      <%= recording_schedule.human_readable_schedule %>
    </p>
    <%= render partial: 'details', locals: { recording_schedule: recording_schedule } %>
  </div>
  <div class="col_2 actions">
    <%= link_to 'Edit', edit_recording_schedule_path(recording_schedule), class: 'button blue' %>
    <%= link_to 'Delete', recording_schedule, method: :delete, data: { confirm: 'Are you sure you want to delete this schedule?' }, class: 'button red' %>
  </div>
  <div class="clearfix"></div>
</div>

app/views/recording_schedules/edit.html.erb
<div class="col_6 middle">
  <%= render partial: 'form', locals: {recording_schedule: @recording_schedule,
    url: recording_schedule_path(@recording_schedule) } %>
</div

app/views/recording_schedules/index.html.erb
<%= render 'no_schedules' unless @recording_schedules.present? %>
<% if @recording_schedules.present? %>
  <div class="recordings">
    <div class="header col_12">
      <%= link_to time_zone_path, class: 'time_zone button' do %>
        <i class="schedule_icon icon-time icon"></i>
        <%= current_user.time_zone %>
      <% end %>
      <%= link_to new_recording_schedule_path, class: 'new_button button green' do %>
        New
      <% end -%>
    </div>

    <% @recording_schedules.each do |recording_schedule| %>
      <%= render partial: 'recording_schedule_card', locals: {recording_schedule: recording_schedule } %>
    <% end %>
  </div>
<% end %>

app/views/recording_schedules/logs/show.html.erb
<div class="recording_log">
  <div class="header col_12">
    <pre><%= @log_content %></pre>
  </div>
</div>

app/views/recording_schedules/new.html.erb
<div class="col_6 middle">
  <%= render partial: 'form', locals: {recording_schedule: @recording_schedule,
      url: recording_schedules_path } %>
</div>

app/views/time_zones/show.html.erb
<div class="col_6 middle">
  <%= form_for current_user, url: time_zone_path do |f| %>
    <p>
      Set the recording clock your local time.
    </p>
    <%= f.time_zone_select :time_zone, /US/, prompt: "Choose your timezone"  %>
    <%= submit_tag 'Save', class: 'button green' %>
  <% end %>
</div>